### ISSUE TITLE
CSS integration issues on Shopify

### ISSUE THREAD

**Issue by yannickcr** [algolia/unified-instantsearch-ecommerce#114]
I integrated `unified-instantsearch-ecommerce` on Shopify (default theme) and I encountered some small CSS issues (conflict between the default styles and `search.css`):

![yannick-algolia myshopify com_](https://user-images.githubusercontent.com/13209/81305133-43715000-907e-11ea-9d13-f3339687af33.png)

* `z-index` problem

On Shopify the `.site-header__mobile-nav` element has a `z-index: 999` which bring it on top of `.uni-Overlay` and `.uni-Container`. Can be solved by setting a `z-index` at 999 (or higher) on these elements.

* padding problem on checkboxes in refinement list

On Shopify `input` and `textarea` have a default padding, which conflict with the custom checkbox style. Can be solved by setting a `padding` at 0 on these elements.

**Comment by sarahdayan** [comment]
Hey @yannickcr, thanks for letting us know!

We've introduced `baseZIndex` in #107 to fix the `z-index issue`, this will solve the problem once we release it.

For the padding we'll take care of it (or you can open a PR if you feel like it 🙂).
