### ISSUE TITLE
Feature: Automatically select input field on open

### ISSUE THREAD

**Issue by skius** [algolia/unified-instantsearch-ecommerce#119]
Currently the user has to press once on the input field that's shown on the website, and then again on the unified overlay. I think it's user-friendlier if the input field was automatically selected and ready to type as soon as the overlay gets loaded. Where would a such an auto-select of the input field best fit in the code?

**Comment by francoischalifour** [comment]
Hi @skius, we'll add this to the next version.

In the meantime, you can use an effect to focus the [input](https://github.com/algolia/unified-instantsearch-ecommerce/blob/8709f4523fea23d6cbbfbdcdc97953308b570cdb/src/components/SearchBox/SearchBox.js#L4) when React mounts it in [`SearchBox.js`](https://github.com/algolia/unified-instantsearch-ecommerce/blob/8709f4523fea23d6cbbfbdcdc97953308b570cdb/src/components/SearchBox/SearchBox.js). It would look like this:

```jsx
function SearchBox() {
  const inputRef = React.useRef(null);

  React.useEffect(() => {
    if (inputRef.current) {
      inputRef.current.focus();
    }
  }, [inputRef]);

  // ...
}
```

**Comment by skius** [comment]
Thanks! That's cleaner than my solution, didn't know about refs 🧼

**Comment by francoischalifour** [comment]
Release in `v0.1.0-beta.1`.
