### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by haloween** [algolia/unified-instantsearch-ecommerce#159]
Installed using yark, cloned fresh. 
Local dev does not start.

**Comment by francoischalifour** [comment]
Can you provide more information from your logs?

**Comment by krishnaapatel** [comment]
If you are using Window OS. update below script in package.json
"start": "SET NODE_ENV=development & webpack-dev-server --config webpack/dev.babel.js --mode=development"

use "SET" before NODE_ENV and use "&" after that.
